# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotifiCar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotifiCar
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'NotifiCar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  end

  target 'NotifiCarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NotifiCar-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotifiCar-tvOS

  # target 'NotifiCar-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
