# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotifiCar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotifiCar
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'NotifiCar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NotifiCarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NotifiCar-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NotifiCar-tvOS

  # target 'NotifiCar-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end
