# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(workspace: "NotifiCar.xcworkspace", scheme: "NotifiCar")
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    sync_code_signing(type: "appstore", app_identifier: "com.jldevs.notificar")
    build_app(
      scheme: "NotifiCar",
      workspace: "NotifiCar.xcworkspace",
      include_bitcode: true
    )
    upload_to_app_store
  end
end
