// Authentication
export const CHECKING_USER_IS_LOGGED = 'CHECKING_USER_IS_LOGGED';
export const USER_IS_NOT_LOGGED = 'USER_IS_NOT_LOGGED';
export const USER_IS_LOGGED = 'USER_IS_LOGGED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const CHECK_USER_TOKEN_DEVICE = 'CHECK_USER_TOKEN_DEVICE';

// Account
export const WRITE_VEHICLE = 'WRITE_VEHICLE';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_ERROR = 'ADD_VEHICLE_ERROR';
export const REMOVE_VEHICLE = 'REMOVE_VEHICLE';
export const SHOW_DIALOG = 'SHOW_DIALOG';
export const UPDATE_VEHICLE_ERROR = 'UPDATE_VEHICLE_ERROR';
export const FETCH_USER_VEHICLES = 'FETCH_USER_VEHICLES';
export const SAVING_VEHICLE = 'SAVING_VEHICLE';
export const FETCH_VEHICLES_IS_LOADING = 'FETCH_VEHICLES_IS_LOADING';

// Feed
export const SHOW_DIALOG_FEED = 'SHOW_DIALOG_FEED';
export const WRITE_VEHICLE_FEED = 'WRITE_VEHICLE_FEED';
export const UPDATE_VEHICLE_ERROR_FEED = 'UPDATE_VEHICLE_ERROR_FEED';
export const OCURRENCE_TYPE_LOAD = 'OCURRENCE_TYPE_LOAD';
export const CHANGE_OCURRENCE_TYPE = 'CHANGE_OCURRENCE_TYPE';
export const OCURRENCE_TYPE_IS_LOADING = 'OCURRENCE_TYPE_IS_LOADING';
export const OCURRENCE_TYPE_LOADING_FINISHED = 'OCURRENCE_TYPE_LOADING_FINISHED';
export const SAVING_OCURRENCE = 'SAVING_OCURRENCE';
export const ADD_OCURRENCE_SUCCESS = 'ADD_OCURRENCE_SUCCESS';
export const ADD_OCURRENCE_ERROR = 'ADD_OCURRENCE_ERROR';
export const FETCH_OCURRENCES_OF_THE_DAY = 'FETCH_OCURRENCES_OF_THE_DAY';
export const FETCH_OCURRENCES_IS_LOADING = 'FETCH_OCURRENCES_IS_LOADING';
