// Authentication
export const CHECKING_USER_IS_LOGGED = 'CHECKING_USER_IS_LOGGED';
export const USER_IS_NOT_LOGGED = 'USER_IS_NOT_LOGGED';
export const USER_IS_LOGGED = 'USER_IS_LOGGED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const CHECK_USER_TOKEN_DEVICE = 'CHECK_USER_TOKEN_DEVICE';
export const REMOVE_USER_ID = 'REMOVE_USER_ID';

// #region Main
export const FETCH_OCCURRENCES_TYPES = 'FETCH_OCCURRENCES_TYPES';
export const FETCH_OCCURRENCES_TYPES_SUCCESS = 'FETCH_OCCURRENCES_TYPES_SUCCESS';
export const FETCH_OCCURRENCES_TYPES_ERROR = 'FETCH_OCCURRENCES_TYPES_ERROR';
// #endregion

// Account
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_ERROR = 'ADD_VEHICLE_ERROR';
export const REMOVE_VEHICLE = 'REMOVE_VEHICLE';
export const FETCH_USER_VEHICLES = 'FETCH_USER_VEHICLES';
export const SAVING_VEHICLE = 'SAVING_VEHICLE';
export const FETCH_VEHICLES_IS_LOADING = 'FETCH_VEHICLES_IS_LOADING';

// Feed
export const SHOW_DIALOG_FEED = 'SHOW_DIALOG_FEED';
export const WRITE_VEHICLE_FEED = 'WRITE_VEHICLE_FEED';
export const UPDATE_VEHICLE_ERROR_FEED = 'UPDATE_VEHICLE_ERROR_FEED';
export const CHANGE_OCCURRENCE_TYPE = 'CHANGE_OCCURRENCE_TYPE';
export const OCCURRENCE_TYPE_IS_LOADING = 'OCCURRENCE_TYPE_IS_LOADING';
export const SAVING_OCCURRENCE = 'SAVING_OCCURRENCE';
export const ADD_OCCURRENCE_SUCCESS = 'ADD_OCCURRENCE_SUCCESS';
export const ADD_OCCURRENCE_ERROR = 'ADD_OCCURRENCE_ERROR';
export const FETCH_OCCURRENCES_OF_THE_DAY = 'FETCH_OCCURRENCES_OF_THE_DAY';
export const FETCH_OCCURRENCES_IS_LOADING = 'FETCH_OCCURRENCES_IS_LOADING';
export const ADD_OCCURRENCE_TYPE_COUNT_SUCCESS = 'ADD_OCCURRENCE_TYPE_COUNT_SUCCESS';
export const ADD_OCCURRENCE_TYPE_COUNT_ERROR = 'ADD_OCCURRENCE_TYPE_COUNT_ERROR';

//Ranking
export const FETCH_OCCURRENCES_TYPE_RANKING_IS_LOADING = 
    'FETCH_OCCURRENCES_TYPE_RANKING_IS_LOADING';
export const FETCH_OCCURRENCES_TYPE_RANKING_LIST = 'FETCH_OCCURRENCES_TYPE_RANKING_LIST';
export const FETCH_OCCURRENCES_TYPE_RANKING_IMAGES = 'FETCH_OCCURRENCES_TYPE_RANKING_IMAGES';
export const FETCH_OCCURRENCES_TYPE_RANKING_TOTAL = 'FETCH_OCCURRENCES_TYPE_RANKING_TOTAL';
